### ISSUE TITLE
selenium出现超时问题

### ISSUE THREAD

**Issue by jfplyl999** [PKUcoldkeyboard/AIBUS-tool#1]
![image](https://github.com/PKUcoldkeyboard/AIBUS-tool/assets/50453655/0ac1e07c-2516-436e-8bbd-b204d5741ef2)

出现超时问题，大佬有办法解决么

**Comment by PKUcoldkeyboard** [comment]
在本地跑是没问题的，可能最近github服务器连接aibus不太稳定吧，建议租云服务器上在上面开个定时任务

**Comment by jfplyl999** [comment]
ok

**Comment by jfplyl999** [comment]
大佬看你跟新的readme，是在ubuntu上运行的把，要在centos或者anolis上运行，要怎样改，我试了安装google有问题

**Comment by PKUcoldkeyboard** [comment]
大概这样？

```shell
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

yum localinstall google-chrome-stable_current_x86_64.rpm

wget https://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip

unzip chromedriver_linux64.zip

mv chromedriver /usr/local/bin/

chmod +x /usr/local/bin/chromedriver
```

**Comment by jfplyl999** [comment]
这个我试过，
![image](https://github.com/PKUcoldkeyboard/AIBUS-tool/assets/50453655/5c58f6aa-2732-4da8-870f-261619bfd29b)
安装google出问题，我在网上找找看看有没有方法解决
